### ISSUE TITLE
Cannot Build APK

### ISSUE THREAD

**Issue by rider8581** [h-mdm/hmdm-plugin-wifimanager#1]
Good day,

I was trying to build the apk but it is making the following error:
![image](https://user-images.githubusercontent.com/52605718/131292982-a69d45c2-1d3a-41d8-b585-c6ef923af9b1.png)

Would you give me comment why this error is happening?

**Comment by h-mdm** [comment]
Fixed by latest push.

Note that the latest version of WiFi manager should be signed by the same keys as Headwind MDM, to get the device owner permissions.

If you don't have keys, please contact the Headwind MDM support to request them.

**Comment by rider8581** [comment]
I have downloaded the latest version but it is still making this error.
Also I tried to install the following APK:
https://m.apkpure.com/wifi-connection/com.wificonnection.booster92
But it asks the Location permission when I run it.
I don't know why it needs location permission. Can you make it scan wifi without location permission?

**Comment by rider8581** [comment]
I can see you disabled the error by adding @SuppressWarnings("MissingPermission").
I tried this but even it built the apk successfully, I couldn't install it on my android since it is saying being corrupted.
