### ISSUE TITLE
Cannot build APK

### ISSUE THREAD

**Issue by rider8581** [h-mdm/hmdm-plugin-wifimanager#2]
Good day, 

Thank you for updating code.
But I still cannot build the latest version.
![image](https://user-images.githubusercontent.com/52605718/131323223-ee18e2d1-d6bd-4f8c-878d-853a72ba1179.png)

It requires keystore.jks which is not shared on github.
Would you share that keystore file too?

**Comment by h-mdm** [comment]
The reference to the keystore has been added to the public code by mistake. This has been fixed.

WiFi manager needs to be signed by the same keys as Headwind MDM (or the shared user com.hmdm should be removed from AndroidManifest.xml, this will make the app unusable on Android 10+). 

The keys are confidential and could not be published. To request the keys, please contact Headwind MDM technical support: https://h-mdm.com/contact-us/ (Signing the NDA may be required).
