### ISSUE TITLE
Cannot build APK

### ISSUE THREAD

**Issue by rider8581** [h-mdm/hmdm-plugin-wifimanager#3]
![image](https://user-images.githubusercontent.com/52605718/131424133-d4197614-ee8f-4082-8ca1-76aced256b88.png)

even I built the APK, it cannot be installed on my Android,
Should I get the key and sign the APK?

**Comment by h-mdm** [comment]
To work on Android 10 and above, the APK must be signed by the same keys as Headwind MDM ("shared" build variant).

You can also build the "main" build variant and sign it by your debug keys, it will work on Android 9 and below.

P.S. Your team lead has contacted Headwind MDM support and I have sent you the keys!
